---
- name: Update apt cache (for Debian family)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present
