# Fichier: tasks/03_setup_database.yml (VERSION FINALE)
---
- name: Ensure MariaDB data directory exists and has correct permissions
  ansible.builtin.file:
    path: /var/lib/mysql
    state: directory
    owner: "{{ db_os_user }}"
    group: "{{ db_os_user }}"
    mode: '0755'

- name: Initialize MariaDB data directory if it is not already initialized
  ansible.builtin.command:
    cmd: "mariadb-install-db --user={{ db_os_user }} --datadir=/var/lib/mysql"
  args:
    creates: /var/lib/mysql/mysql
  changed_when: true

- name: (Cleanup) Ensure no old MariaDB processes are running
  ansible.builtin.command:
    cmd: "pkill -f mariadb || true"
  changed_when: false

- name: Start MariaDB process directly
  ansible.builtin.shell:
    cmd: "mysqld_safe --datadir=/var/lib/mysql &"
  args:
    creates: /var/run/mysqld/mysqld.sock
  changed_when: true

- name: Wait for MariaDB socket to be ready before proceeding
  ansible.builtin.wait_for:
    path: /var/run/mysqld/mysqld.sock
    state: present
    timeout: 60
    delay: 5

- name: Set MariaDB root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ db_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous MariaDB users
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Remove MariaDB test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    host: localhost
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
