---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install required packages
  ansible.builtin.include_tasks: 02_install_packages.yml

- name: Configure and secure the database
  ansible.builtin.include_tasks: 03_setup_database.yml

- name: Download and configure WordPress
  ansible.builtin.include_tasks: 04_setup_wordpress.yml

- name: Configure the web server
  ansible.builtin.include_tasks: 05_setup_webserver.yml
